# Generated by Django 2.0.2 on 2018-02-16 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20180214_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
