# Generated by Django 2.0.2 on 2018-02-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180217_1951'),
        ('posts', '0006_comment'),
    ]

    operations = [
    ]
