# Generated by Django 2.0.2 on 2018-02-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_merge_20180219_1821'),
        ('posts', '0007_auto_20180220_1050'),
        ('posts', '0004_remove_post_headline'),
    ]

    operations = [
    ]
