# Generated by Django 2.0.2 on 2018-02-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_merge_20180220_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
